import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.0.0"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: req.headers.get('Authorization')! } } }
    )

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser()
    if (userError || !user) throw new Error('Unauthorized')

    // Check credits
    const { data: credits, error: creditError } = await supabaseClient
      .from('usage_credits')
      .select('daily_journal_credits')
      .eq('user_id', user.id)
      .single()

    if (creditError || !credits || credits.daily_journal_credits <= 0) {
       return new Response(JSON.stringify({ error: 'Insufficient credits' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 403,
      })
    }

    const { text, date } = await req.json()

    if (!text || !date) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: text and date' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      )
    }

    // Insert raw journal entry (summary will be auto-generated by webhook)
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const { data: insertedEntry, error: insertError } = await supabaseAdmin
      .from('journal_entries')
      .insert({
        user_id: user.id,
        journal_date: date,
        date: date, // String format
        raw_transcript: text,
        summary: null, // Will be filled by auto-summarize webhook
        is_summarized: false,
      })
      .select()
      .single()

    if (insertError) throw insertError

    // Return success - summary will be generated asynchronously by webhook
    return new Response(JSON.stringify({
      status: 'processing',
      message: 'Journal entry created. Summary will be generated shortly.',
      entry_id: insertedEntry.id,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 202, // 202 Accepted - processing async
    })

  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    })
  }
})
